services:
  backend:
    build: ./backend
    container_name: web-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:pass@db:5432/dream_work
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret_password
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: dream_work
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dream_work
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d dream_work" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    healthcheck:
      test: [ "CMD", "redis-cli",  "ping", "-a", "secret_password"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    environment:
      - REDIS_PASSWORD=secret_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command:
      ["redis-server", "--requirepass", "secret_password"]
    ports:
      - "6379:6379"

