"""chanhed simulation table, commented expected_income and roi

Revision ID: 51693ac290f5
Revises: 5d1a80f1a27a
Create Date: 2026-03-26 19:31:40.986750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51693ac290f5'
down_revision: Union[str, Sequence[str], None] = '5d1a80f1a27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'expected_income')
    op.drop_column('simulations', 'roi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('roi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('simulations', sa.Column('expected_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
