"""chanhed simulation table

Revision ID: bc1f3d9a9154
Revises: c4e9def80628
Create Date: 2026-03-27 20:30:28.292043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1f3d9a9154'
down_revision: Union[str, Sequence[str], None] = 'c4e9def80628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('recommended_skills', sa.JSON(), nullable=False))
    op.alter_column('simulations', 'time_estimate',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
                postgresql_using='to_json(time_estimate)',
               existing_nullable=False)
    op.alter_column('simulations', 'market_analysis',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                    postgresql_using='to_json(time_estimate)',
               existing_nullable=False)
    op.alter_column('simulations', 'salary_growth',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('skills', sa.Column('simulation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'skills', 'simulations', ['simulation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'simulation_id')
    op.alter_column('simulations', 'salary_growth',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('simulations', 'market_analysis',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('simulations', 'time_estimate',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('simulations', 'recommended_skills')
    # ### end Alembic commands ###
