"""chanhed RefershToken table

Revision ID: bec60f8f12d6
Revises: cc985760fa4b
Create Date: 2026-03-29 19:05:44.717070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec60f8f12d6'
down_revision: Union[str, Sequence[str], None] = 'cc985760fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('token_blacklist', sa.Column('hashed_token', sa.String(), nullable=False))
    op.add_column('token_blacklist', sa.Column('expired_at', sa.String(), nullable=False))
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_hashed_token'), 'token_blacklist', ['hashed_token'], unique=False)
    op.create_foreign_key(None, 'token_blacklist', 'users', ['user_id'], ['id'])
    op.drop_column('token_blacklist', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'token_blacklist', type_='foreignkey')
    op.drop_index(op.f('ix_token_blacklist_hashed_token'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=False)
    op.drop_column('token_blacklist', 'expired_at')
    op.drop_column('token_blacklist', 'hashed_token')
    op.drop_column('token_blacklist', 'user_id')
    # ### end Alembic commands ###
