"""chanhed simulation table

Revision ID: c4e9def80628
Revises: 51693ac290f5
Create Date: 2026-03-26 19:39:57.324005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4e9def80628'
down_revision: Union[str, Sequence[str], None] = '51693ac290f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('time_estimate', sa.Integer(), nullable=False))
    op.add_column('simulations', sa.Column('market_analysis', sa.String(), nullable=False))
    op.add_column('simulations', sa.Column('salary_growth', sa.Integer(), nullable=False))
    op.drop_column('simulations', 'result_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('simulations', 'salary_growth')
    op.drop_column('simulations', 'market_analysis')
    op.drop_column('simulations', 'time_estimate')
    # ### end Alembic commands ###
